[project]
name = "temperatures-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django~=6.0",
    "pywebpush~=2.1",
    "dj-database-url~=3.0",
]
